### PR TITLE
first and second test for profile page

### PR DESCRIPTION
**Pull request by hrafov**

### CODE REVIEW

**Review by hrafov — COMMENTED** [review]
I hide my password

**Review by KnazevValeriy — COMMENTED** [review]
Simplify your xpathes

**Review by hrafov — COMMENTED** [review]
more simple xpath

**Review by KnazevValeriy — DISMISSED** [review]
nice!

**Review by hrafov — COMMENTED** [review]
I added assests to second test

**Review by KnazevValeriy — DISMISSED** [review]

**Comment by hrafov** [comment]
not undestandable - may by its not right to change files in pullrequest

**Review by KnazevValeriy — APPROVED** [review]

**Pull request closed without merging**
